INSERT OR REPLACE INTO heroes_mst (hero_id, hero_name, role_id, slug, top500_kda, top500_damage_per_minutes, top500_damage_taken_per_minutes, top500_healing_per_minutes) VALUES
(1042, 'Peni Parker', 0, 'peni-parker', NULL, NULL, NULL, NULL),
(1023, 'Rocket Raccoon', 2, 'rocket-raccoon', NULL, NULL, NULL, NULL),
(1029, 'Magik', 1, 'magik', NULL, NULL, NULL, NULL),
(1015, 'Storm', 1, 'storm', NULL, NULL, NULL, NULL),
(1028, 'Ultron', 2, 'ultron', NULL, NULL, NULL, NULL),
(1020, 'Mantis', 2, 'mantis', NULL, NULL, NULL, NULL),
(1040, 'Mister Fantastic', 1, 'mister-fantastic', NULL, NULL, NULL, NULL),
(1055, 'Daredevil', 1, 'daredevil', NULL, NULL, NULL, NULL),
(1011, 'Hulk', 0, 'hulk', NULL, NULL, NULL, NULL),
(1022, 'Captain America', 0, 'captain-america', NULL, NULL, NULL, NULL),
(1056, 'Angela', 0, 'angela', NULL, NULL, NULL, NULL),
(1065, 'Rogue', 0, 'rogue', NULL, NULL, NULL, NULL),
(1044, 'Blade', 1, 'blade', NULL, NULL, NULL, NULL),
(1039, 'Thor', 0, 'thor', NULL, NULL, NULL, NULL),
(1052, 'Iron Fist', 1, 'iron-fist', NULL, NULL, NULL, NULL),
(1018, 'Doctor Strange', 0, 'doctor-strange', NULL, NULL, NULL, NULL),
(1051, 'The Thing', 0, 'the-thing', NULL, NULL, NULL, NULL),
(1017, 'Human Torch', 1, 'human-torch', NULL, NULL, NULL, NULL),
(1026, 'Black Panther', 1, 'black-panther', NULL, NULL, NULL, NULL),
(1016, 'Loki', 2, 'loki', NULL, NULL, NULL, NULL),
(1060, 'White Fox', 2, 'white-fox', NULL, NULL, NULL, NULL),
(1043, 'Star-lord', 1, 'star-lord', NULL, NULL, NULL, NULL),
(1063, 'Cyclops', 1, 'cyclops', NULL, NULL, NULL, NULL),
(1027, 'Groot', 0, 'groot', NULL, NULL, NULL, NULL),
(1062, 'Devil Dinosaur', 0, 'devil-dinosaur', NULL, NULL, NULL, NULL),
(1046, 'Adam Warlock', 2, 'adam-warlock', NULL, NULL, NULL, NULL),
(10571, 'Deadpool (Vanguard)', 0, 'deadpool-vanguard', NULL, NULL, NULL, NULL),
(10572, 'Deadpool (Duelist)', 1, 'deadpool-duelist', NULL, NULL, NULL, NULL),
(10573, 'Deadpool (Strategist)', 2, 'deadpool-strategist', NULL, NULL, NULL, NULL),
(1049, 'Wolverine', 1, 'wolverine', NULL, NULL, NULL, NULL),
(1035, 'Venom', 0, 'venom', NULL, NULL, NULL, NULL),
(1024, 'Hela', 1, 'hela', NULL, NULL, NULL, NULL),
(1034, 'Iron Man', 1, 'iron-man', NULL, NULL, NULL, NULL),
(1025, 'Cloak &Dagger', 2, 'cloak-dagger', NULL, NULL, NULL, NULL),
(1036, 'Spider-man', 1, 'spider-man', NULL, NULL, NULL, NULL),
(1050, 'Invisible Woman', 2, 'invisible-woman', NULL, NULL, NULL, NULL),
(1053, 'Emma Frost', 0, 'emma-frost', NULL, NULL, NULL, NULL),
(1048, 'Psylocke', 1, 'psylocke', NULL, NULL, NULL, NULL),
(1041, 'Winter Soldier', 1, 'winter-soldier', NULL, NULL, NULL, NULL),
(1031, 'Luna Snow', 2, 'luna-snow', NULL, NULL, NULL, NULL),
(1038, 'Scarlet Witch', 1, 'scarlet-witch', NULL, NULL, NULL, NULL),
(1037, 'Magneto', 0, 'magneto', NULL, NULL, NULL, NULL),
(1059, 'Elsa Bloodstone', 1, 'elsa-bloodstone', NULL, NULL, NULL, NULL),
(1061, 'Black Cat', 1, 'black-cat', NULL, NULL, NULL, NULL),
(1045, 'Namor', 1, 'namor', NULL, NULL, NULL, NULL),
(1014, 'The Punisher', 1, 'the-punisher', NULL, NULL, NULL, NULL),
(1058, 'Gambit', 2, 'gambit', NULL, NULL, NULL, NULL),
(1047, 'Jeff The Land Shark', 2, 'jeff-the-land-shark', NULL, NULL, NULL, NULL),
(1021, 'Hawkeye', 1, 'hawkeye', NULL, NULL, NULL, NULL),
(1032, 'Squirrel Girl', 1, 'squirrel-girl', NULL, NULL, NULL, NULL),
(1054, 'Phoenix', 1, 'phoenix', NULL, NULL, NULL, NULL),
(1030, 'Moon Knight', 1, 'moon-knight', NULL, NULL, NULL, NULL),
(1033, 'Black Widow', 1, 'black-widow', NULL, NULL, NULL, NULL);
